# Default values for ExampleApp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# name: value

app:
  Memory: "200Mi"
  Cpu: "100m"
  Name: example-app
  Image: "registry.wdo.io/k8swar/exampleapp"
  ImageTag: "0.1.0"
  ImagePullPolicy: "Always"
  Replicas: 1
# Exposes parameter
  ServicePort: 80
  ContainerPort: 8080
  # NodePort: <to set explicitly, choose port between 30000-32767
  NodePort: 30055
  externalIPs: "192.168.99.100"
  ServiceType: NodePort
#  If ServiceType need specify parameter LoadBalancerSourceRanges
#  LoadBalancerSourceRanges:
#  - 10.144.192.0/20

db:
  Cpu: "200m"
  Memory: "512Mi"
  Name: example-db
  ImageDb: "registry.wdo.io/k8swar/exampledb"
  ImageTagDb: "0.1.0"
  ImagePullPolicy: "Always"
  ServicePort: 5432
# DB parameter
  db_user: 'postgres'
  db_name: 'blog'
  db_pass: 'postgres'
  db_port: '5432'
  db_path: '/var/lib/postgresql/data/'
# Disk parameter
  Persistence:
     Enabled: true
     AccessMode: ReadWriteOnce
     Size: 2Gi
     type: hostpath
     path: "/tmp/data/pv-1"
     #type: nfs
     #nfspath: '/opt/nfs/exampleapp'
     #nfsserver: 10.18.99.1
