{{- if .Values.app.HostName }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
spec:
  rules:
  - host: {{ .Values.app.HostName | quote }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "fullname" . }}
            servicePort: {{ .Values.app.ServicePort }}
{{- end }}
