apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: {{ template "postgresql.fullname" . }}
spec:
  ports:
    - port: {{.Values.db.ServicePort}}
      name: db
      targetPort: {{.Values.db.db_port}}
  selector:
    app: {{ template "postgresql.fullname" . }}
